server:
  port: 8082 #服务器端口
  servlet:
    context-path: /servicearrange #应用的上下文路径

spring:
  application:
    name: servicearrange #项目名称
  #rabbitmq配置
  cloud:
    stream:
      binders:
        rabbit_cluster:
          environment:
            spring:
              rabbitmq:
                addresses: 8.129.116.16:5672
                password: guest
                username: guest
          type: rabbit
      bindings:
        output_channel:
          binder: rabbit_cluster
          content-type: application/json
          destination: ${spring.application.name}-exchange-point
        shell_task_status_channel:
          binder: rabbit_cluster
          content-type: application/json
          destination: ${spring.application.name}-exchange-point
          group: ${task.shell_task_status}
        task_result_input_channel:
          binder: rabbit_cluster
          consumer:
            concurrency: 1
          content-type: application/json
          destination: ${spring.application.name}-exchange-point
          group: ${task.result_queue_name}
        task_run_input_channel:
          binder: rabbit_cluster
          consumer:
            concurrency: 1
          content-type: application/json
          destination: ${spring.application.name}-exchange-point
          group: ${task.run_queue_name}
      rabbit:
        bindings:
          output_channel:
            producer:
              routing-key-expression: headers.receiveSign
          shell_task_status_channel:
            consumer:
              binding-routing-key: ${{task.shell_task_status}
          task_result_input_channel:
            consumer:
              acknowledge-mode: manual
              binding-routing-key: ${task.result_queue_name}
          task_run_input_channel:
            consumer:
              acknowledge-mode: manual
              binding-routing-key: ${task.run_queue_name}
  #mongodb配置
  data:
    mongodb:
      database: admin
      host: 8.129.116.16
      password: 123456
      port: 27017
      username: admin
  #指定打包环境
  profiles:
    active: jar

#zk配置
zk:
  session-timeout: 5000
  url: 8.129.116.16:2181

task:
  result_queue_name: /task/result
  run_queue_name: /task/run